version: '3'
services:
  mongo:
    container_name: mern-db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mern-microservices-1-network
  backend:
    container_name: mern-backend
    image: mern-microservices-1-backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
<<<<<<< HEAD
      - MONGODB_URI=mongodb://root:example@mern-db:27017/microservices-test
=======
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo:27017/microservices-test
>>>>>>> 712f8c2ce6c5c39ea4c1d12bd316da2dc220ac18
    networks:
      - mern-microservices-1-network
  frontend:
    container_name: mern-frontend      
    image: mern-microservices-1-frontend
    restart: always
    ports:
      - '80:80'
    networks:
      - mern-microservices-1-network

networks:
  mern-microservices-1-network:
    external:
      name: mern-microservices-1-network
