FROM mongo:latest

# Install the MongoDB client tools
RUN apt-get update && \
    apt-get install -y mongodb-clients

# Copy the init-db.sh script into the container
COPY init-db.sh /usr/src/init-db.sh

EXPOSE 27017

# Make the script executable
RUN chmod +x /usr/src/init-db.sh

# Run the script when the container starts up
CMD ["/bin/sh", "/usr/src/init-db.sh"]
