FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./*.js ./
COPY ./database ./database
COPY ./handlers ./handlers
COPY ./services ./services
COPY ./config ./config

EXPOSE 5000

CMD ["node", "app.js"]
