# Use the official MongoDB image as the base image
FROM mongo:latest

# Install gnupg and wget
RUN apt-get update && \
    apt-get install -y gnupg wget && \
    wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - && \
    echo "deb [ arch=amd64,arm64 ] <REPLACE_WITH_MONGODB_REPO_URL> multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
    apt-get update && \
    apt-get install -y mongodb-org-tools && \
    rm -rf /var/lib/apt/lists/*

# Copy the init-db.sh script into the container
COPY init-db.sh /usr/src/init-db.sh

# Make the script executable
RUN chmod +x /usr/src/init-db.sh

# Expose the default MongoDB port
EXPOSE 27017

# Run the initialization script when the container starts up
CMD ["/usr/src/init-db.sh"]
